#!/usr/bin/env bash

# brew install jq pv zstd

set -euo pipefail

mount.sh

DESTINATION=/Volumes/minio/docker-images
TMPFILE=$(mktemp $DESTINATION/backup-docker-images-XXXXX)
trap 'rm -f $TMPFILE' EXIT
echo "tmpfile is $TMPFILE"

docker images | tail -n +2 | grep -v "none" | while read -r LINE
do
    image_id=$(echo "$LINE" | awk '{print $3}')
    filename=$(echo "$LINE" | awk -vhostname="$(hostname)" '{printf $1 "_" $2 "_" hostname "_" $3}')
    echo "filename is $filename"
    compress_target="$DESTINATION"/"$filename".tar.zst
    [ -f "$compress_target" ] && continue

    size=$(docker inspect "$image_id" | jq -r '.[].Size')
    image_tag=$(docker inspect cda51f0affc9 | jq -r '.[].RepoTags[0]')
    nice -n 19 bash -c 'docker save '"$image_tag"' | pv --cursor --size '"$size"' --buffer-size 1024 -N "'"$filename"' docker save" | zstd -q -19 -T0 | pv --cursor --buffer-size 1024 -N "'"$filename"' zstd compress" > '"$TMPFILE"
    mv "$TMPFILE" "$compress_target"
done
