#!/usr/bin/env bash

set -euxo pipefail

nice -n 19 taskpolicy -c background yt-dlp \
    -f "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4] / bv*+ba/b" \
    --keep-video \
    --no-keep-fragments \
    --sub-langs "en.*" \
    --no-embed-thumbnail \
    --embed-metadata \
    --no-embed-chapters \
    --ffmpeg-location $(which ffmpeg) \
    "$@"
