#!/usr/bin/env bash

set -euxo pipefail

brew install git ripgrep
brew install coreutils fd
xcode-select --install || true
rustup component add rls
rustup component add clippy

# dictionary
brew install wordnet
brew install sqlite

# flyspell
brew install aspell

# flycheck
brew install shellcheck
brew install hadolint
brew install markdownlint-cli
npm install --global textlint
npm install --global prettier
brew instal tidy-html5
npm install --global eslint
npm install --global yaml-language-server
npm install --global bash-ls
brew install shfmt
go install golang.org/x/tools/gopls@latest

# textlint
npm install textlint-rule-en-capitalization
npm install textlint-rule-en-spell
npm install textlint-rule-doubled-spaces

brew tap railwaycat/emacsmacport
brew install emacs-mac --with-native-comp --with-mac-metal --with-modules

if [ ! -d "$HOME"/.emacs.d ]; then
    git clone https://github.com/hlissner/doom-emacs "$HOME"/.emacs.d
    doom install
    doom upgrade
    doom sync
    doom env
fi
