#!/usr/bin/env bash

set -euxo pipefail

brew install git ripgrep
brew install coreutils fd
xcode-select --install || true
rustup component add rls
rustup component add clippy

# dictionary
brew install wordnet
brew install sqlite

# flyspell
brew install aspell

# flycheck
brew install shellcheck
brew install hadolint
npm install --global markdownlint-cli
npm install --global textlint
npm install --global prettier
brew instal tidy-html5
npm install --global eslint
npm install --global yaml-language-server
npm install --global bash-ls
brew install shfmt

brew tap railwaycat/emacsmacport
brew install emacs-mac --with-native-comp --with-mac-metal --with-modules

if [ ! -d $HOME/.emacs.d ]
then
    git clone https://github.com/hlissner/doom-emacs $HOME/.emacs.d
    doom install
    doom upgrade
    doom sync
    doom env
fi
