#!/usr/bin/env bash

set -euo pipefail

brew install coreutils
brew install exa
brew install make
brew install plantuml
brew install rsync
brew install tidy-html5
brew install vivid
brew install zstd
