"$schema" = "https://starship.rs/config-schema.json"

# Do not insert a blank line at the beginning of the prompt.
add_newline = false

format = "${custom.my_directory}$line_break$character"

[directory]
home_symbol = ""
truncation_length = 2
style = "bold cyan"
format = "[ $path ]($style)"

[character]
# Use a simple arrow for the prompt.
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[custom.my_directory]
command = "bash -c 'pwd | sed \"s:^$HOME:~:\"'"
format = "[$output](bold cyan) "
