sourceDir = "~/.dotfiles/chezmoi"
encryption = "age"

[sourceVCS]
command = "git"

[edit]
command = "code"
args = ["--wait"]

[diff]
command = "meld"
args = ["--diff", "{{ .Destination }}", "{{ .Target }}"]

[merge]
command = "meld"

[data]
sourceDir = "~/.dotfiles/chezmoi"

[age]
identity = "{{ onepasswordRead \"op://Private/Chezmoi age key/notesPlain\" }}"
recipient = "age1n5dftqq8nmufwz9nr8jnk6yr04ad9wpf5vtws43854k9wgn644ksz6vmqv"
