#!/usr/bin/env python3


import concurrent.futures
import os.path
import subprocess


def patch_font(input_file, glyph_dir, output_dir):
    print(f"patching {input_file}...")
    subprocess.check_call(
        "/build/font-patcher --quiet --mono --adjust-line-height "
        f"--complete --careful --glyphdir {glyph_dir} "
        f" -out {output_dir} -- {input_file}",
        shell=True,
    )
    print(f"patched {input_file}.")


def main() -> None:
    with concurrent.futures.ProcessPoolExecutor() as executor:
        for root, dirs, files in os.walk("/build/dist/iosevka-custom/ttf"):
            for name in files:
                fullpath = os.path.join(root, name)
                executor.submit(
                    patch_font,
                    input_file=fullpath,
                    glyph_dir="/root/glyphs/",
                    output_dir=root,
                )


if __name__ == "__main__":
    main()
