file_opener = "cursor"
approval_policy = "on-failure"
sandbox_mode = "workspace-write"
model = "gpt-5-codex"
model_reasoning_effort = "high"
experimental_use_rmcp_client = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.fetch]
command = "uvx"
args = ["mcp-server-fetch"]

[mcp_servers.aws-api]
command = "uvx"
args = ["awslabs.aws-api-mcp-server@latest"]
env = { "AWS_REGION"="us-west-2" }

[mcp_servers.aws_docs]
command = "uvx"
args = ["fastmcp", "run", "https://knowledge-mcp.global.api.aws"]

[mcp_servers.go-language-server]
command = "mcp-language-server"
args = ["--workspace", ".", "--lsp", "gopls"]

[mcp_servers.rust-language-server]
command = "mcp-language-server"
args = ["--workspace", ".", "--lsp", "rust-analyzer"]

[mcp_servers.python-language-server]
command = "mcp-language-server"
args = ["--workspace", ".", "--lsp", "pyright-langserver", "--", "--stdio"]

[tools]
web_search = true
