file_opener = "cursor"
approval_policy = "on-failure"
sandbox_mode = "workspace-write"

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
 command = "npx"

[profiles.gpt-5]
model = "gpt-5-codex"
model_provider = "openai"
