file_opener = "cursor"
approval_policy = "on-failure"
sandbox_mode = "workspace-write"
model = "gpt-5-codex"
model_reasoning_effort = "high"
experimental_use_rmcp_client = true

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp"]
command = "npx"

[mcp_servers.rust-analyzer-mcp]
command = "rust-analyzer-mcp"

[mcp_servers.fetch]
command = "uvx"
args = ["mcp-server-fetch"]

[mcp_servers.aws-api]
command = "uvx"
args = ["awslabs.aws-api-mcp-server@latest"]
env = { "AWS_REGION": "us-west-2" }

[mcp_servers.aws_docs]
command = "uvx"
args = ["fastmcp", "run", "https://knowledge-mcp.global.api.aws"]

[tools]
web_search = true
