[tool.poetry]
name = "pythonbin"
version = "0.1.0"
description = ""
authors = ["Asim Ihsan"]
readme = "README.md"

[tool.poetry.scripts]
update-workspace = "pythonbin.git.update_workspace:main"
ghreview = "pythonbin.gh.ghreview:main"
compress-logs = "pythonbin.logs.compress:run_main"
load = "pythonbin.load.load:run_main"

[tool.poe.tasks.scrape]
script = "pythonbin.scraper.scrape:run_main"
help = "Scrape a URL"

[[tool.poe.tasks.scrape.args]]
name = "url"
help = "URL to scrape"
options = ["--url"]
type = "string"

[tool.poetry.dependencies]
python = "^3.11"
gitpython = "^3.1.40"
questionary = "^2.0.1"
rich = "^13.7.0"
pydantic = "^2.5.3"
pathspec = "^0.12.1"
playwright = "^1.40.0"
boilerpy3 = "^1.0.7"
beautifulsoup4 = "^4.12.2"
html5lib = "^1.1"
zstandard = "^0.22.0"
psutil = "^5.9.7"
litellm = "^1.16.16"
semver = "^3.0.2"
markdown-it-py = {extras = ["plugins"], version = "^3.0.0"}
mdformat = "^0.7.17"
mistletoe = "^1.2.1"
tree-sitter = "^0.20.4"
scipy = "^1.12.0"
numpy = "^1.26.4"
jira = "^3.6.0"
dateparser = "^1.2.0"
markdown = "^3.6"
numpydoc = "^1.6.0"
pynput = "^1.7.6"
librosa = "^0.10.1"
jupyter = "^1.0.0"
pyautogui = "^0.9.54"
pillow = "^10.2.0"
opencv-python = "^4.9.0.80"
pyscreeze = "^0.1.30"

[tool.poetry.group.dev.dependencies]
black = "^24.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
