[tool.poetry]
name = "pythonbin"
version = "0.1.0"
description = ""
authors = ["Asim Ihsan"]
readme = "README.md"

[tool.poetry.scripts]
update-workspace = "pythonbin.git.update_workspace:main"
ghreview = "pythonbin.git.ghreview:main"

[tool.poetry.dependencies]
gitpython = "^3.1.40"
python = "^3.12"
questionary = "^2.0.1"
rich = "^13.7.0"
pydantic = "^2.5.2"
pathspec = "^0.12.1"

[tool.poetry.group.dev.dependencies]
black = "^23.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
