[tool.poetry]
name = "pythonbin"
version = "0.1.0"
description = ""
authors = ["Asim Ihsan"]
readme = "README.md"

[tool.poetry.scripts]
update-workspace = "pythonbin.git.update_workspace:main"
ghreview = "pythonbin.gh.ghreview:main"
compress-logs = "pythonbin.logs.compress:run_main"

[tool.poe.tasks.scrape]
script = "pythonbin.scraper.scrape:run_main"
help = "Scrape a URL"

[[tool.poe.tasks.scrape.args]]
name = "url"
help = "URL to scrape"
options = ["--url"]
type = "string"

[tool.poetry.dependencies]
gitpython = "^3.1.41"
python = "^3.12"
questionary = "^2.0.1"
rich = "^13.7.0"
pydantic = "^2.5.3"
pathspec = "^0.12.1"
playwright = "^1.40.0"
boilerpy3 = "^1.0.7"
beautifulsoup4 = "^4.12.2"
html5lib = "^1.1"
zstandard = "^0.22.0"
psutil = "^5.9.7"

[tool.poetry.group.dev.dependencies]
black = "^23.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
